#!/bin/sh

SCRIPT=$(readlink -f "$0")
SCRIPTPATH=$(dirname "$SCRIPT")

cd "$SCRIPTPATH"

echo "mkdir -h"
../bin/mkdir.js -h
if [ "$?" != "0" ]; then exit 1; fi

echo "mkdir -V"
../bin/mkdir.js -V
if [ "$?" != "0" ]; then exit 1; fi

rm -rf out
mkdir out

echo "mkdir -D out/a"
../bin/mkdir.js -D out/a
if [ "$?" != "0" ]; then exit 1; fi
if [ -d "out/a" ]; then exit 1; fi

echo "mkdir out/a"
../bin/mkdir.js out/a
if [ "$?" != "0" ]; then exit 1; fi
if [ ! -d "out/a" ]; then exit 1; fi

echo "mkdir -- out/b"
../bin/mkdir.js -- out/b
if [ "$?" != "0" ]; then exit 1; fi
if [ ! -d "out/b" ]; then exit 1; fi

echo "mkdir out/a"
../bin/mkdir.js out/a
if [ "$?" != "1" ]; then exit 1; fi

echo "mkdir -p out/a"
../bin/mkdir.js -p out/a
if [ "$?" != "0" ]; then exit 1; fi

echo "done"
